# Generated by Django 5.0.7 on 2024-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
